//Login
export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE'
export const FETCH_LOGOUT_REQUEST = 'FETCH_LOGOUT_REQUEST'
//LoginWithGoogle
export const LOGIN_WITH_GOOGLE_REQUEST = 'LOGIN_WITH_GOOGLE_REQUEST'
export const LOGIN_WITH_GOOGLE_SUCCESS = 'LOGIN_WITH_GOOGLE_SUCCESS'
export const LOGIN_WITH_GOOGLE_FAILURE = 'LOGIN_WITH_GOOGLE_FAILURE'
//Register
export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST'
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS'
export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE'
