export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'


export const FEATURED_PRODUCT_REQUEST = 'FEATURED_PRODUCT_REQUEST'
export const FEATURED_PRODUCT_SUCCESS = 'FEATURED_PRODUCT_SUCCESS'
export const FEATURED_PRODUCT_FAILURE = 'FEATURED_PRODUCT_FAILURE'

export const LATEST_PRODUCT_REQUEST = 'LATEST_PRODUCT_REQUEST'
export const LATEST_PRODUCT_SUCCESS = 'LATEST_PRODUCT_SUCCESS'
export const LATEST_PRODUCT_FAILURE = 'LATEST_PRODUCT_FAILURE'