export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';

export const POST_CART_REQUEST = 'POST_CART_REQUEST';
export const POST_CART_SUCCESS = 'POST_CART_SUCCESS';
export const POST_CART_FAILURE = 'POST_CART_FAILURE';

export const PUT_CART_REQUEST = 'PUT_CART_REQUEST';
export const PUT_CART_SUCCESS = 'PUT_CART_SUCCESS';
export const PUT_CART_FAILURE = 'PUT_CART_FAILURE';

export const DEL_CART_REQUEST = 'DEL_CART_REQUEST';
export const DEL_CART_SUCCESS = 'DEL_CART_SUCCESS';
export const DEL_CART_FAILURE = 'DEL_CART_FAILURE';